name: python file
#on: push
workflow_dispatch: 
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Run script
        run: python hello.py